### ISSUE TITLE
Game Over

### ISSUE THREAD

**Issue by dvanmali** [UCSB-CS56-Projects/cs56-games-poker#28]
When you finish playing the game, we don't want to exit the game. Rather, create a new screen that can take us back to the Main Menu if you want. The only thing that should let us completely close the game should be EXIT_ON_CLOSE button on the frame. What you can also do with the Game Over screen is also display reasons to why the game is over such as "You ran out of chips to start a new game" or "Opponent ran out chips to start a new game."

Estimate: ~200 points

**Comment by jalexanderqed** [comment]
This may have been solved somewhat over-zealously since now the number of chips each player has is reset at the end of each turn. Please implement the (pre-M16) behavior where the number of chips is maintained until one player runs out of chips. At that point, display a game-over screen with the option to continue.

**Comment by jalexanderqed** [comment]
F16 OK (100 pts)

**Comment by jalexanderqed** [comment]
The number of chips is now maintained, but there is still no "Game Over" screen to indicate that the chips are being reset (even though this is done correctly). Please add this in future.

**Comment by sean-shelton** [comment]
F17 OK (100 pts)
