### ISSUE TITLE
Create a Poker Server with Chat Server Functionality

### ISSUE THREAD

**Issue by dvanmali** [ucsb-cs56-projects/cs56-games-poker#39]
Create a Server interface that relays information between the chat and the poker game servers without needing two separate classes.

Estimate: ~300

**Comment by mcaccamo** [comment]
m16 okay

**Comment by mcaccamo** [comment]
m16 okay

**Comment by jalexanderqed** [comment]
Since the multiplayer server was eliminated in M16 in favor of cleaner codebase, it falls to you to reimplement the multiplayer server while continuing to follow the factory design pattern established in M16. This server should allow two (or more, for more credit) players to play against one another and should incorporate chat functionality instead of requiring a separate chat server. For this reason, it could be implemented on top of the existing chat server if this is found to be practical.

**Comment by jalexanderqed** [comment]
F16 OK (300 pts)

**Comment by sean-shelton** [comment]
F17 OK (300 pts)

**Comment by Sierrasch** [comment]
This issue has been changed and partially completed a couple times over the past couple years which is just making this issue confusing. I'm closing this issue and opening new issues that more clearly state these goals.
